language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: fJDMr7Mvol6ua8eqPgNXGiTxIy58cluMiLlp4SlXpyG3CpHo3D9z6soZgLjFrCxWcEgD1ZjPEoKCf8zb15jA7mWMQWcOlPMstmPLNGPrHrYR96eGypc0si5uyXbuOJj158szMaDlamHiks1g54MvQGLFTu+xAp0Pom8j6awxu4HdUqhFrjtIGL3anBoGi+ZhW3Sznh7VGbkMswJFd3iCIOkZDqKV9a847J+bn6bHp7KiNhDfLYcTda8P5cTaXyfMhGgCO8O4AyvhH0fsXmf+hqqqJrbHJTt7MfUh225Ww/zQy+OjFb18YeT1vrMsOfb8y0NTRyFxBYTiRAkFxCk2eT6t7RZjkw3SA76MUO23A5yLYaEIs/WkP8+rG3qrhDDMCfs9MrXYRrSJ1wcRZXMGDiCmj+gAjJ4TCNS1HYf1Fhi1FdRIKItsrnXdi23Ry8v4f5DPS5xLzTK12aftvlLLYqjjkwG8k40zHZz26EX8Y49vOCGIils8+izClIIVc/mG5kswE19LX2qHcCawn9gN9ZR5qJIRil6dKLaqbVdaqLX+fWgrn8317C8cZdrwg/1PfvCKny5NiJTd5TuMWaBixz+PjzR6GZjthU6qOUmPpO5WGRdYbl++958uMR/eJhGvUprPltTNZBRV3fEmTUdWNH6xPm00COKPFKy+3SZiCsg=
  app: gentle-hollows-75217
  on:
    repo: mike-crane/dibs-server
