language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: K4YQ532R8VZbnlsHrXiQdHP0SGfk7rIVpUB7FWLVhe+QV3YM9M2SmQFdxJqXJTmmiZYqx6cwacTDYPA7C+/o85iR3LyUSfI5N9Vm/2OdcwmzJTISKIKEKYyxZqXF1t+qPMyuuN47XhuEFADoW0lmUm3ZdObPNIFOodF9fnZq6ACJEpBUQUOR9FNTk39NoX3UWO4kraRO1WWloBekleAOCNH6TC78OsfpGDen8H4ISYnJH6Bch+AOfFcRoq60lAzcplJjUTiYVANCkqKwFWiqxwvgUx0FQTEi4QZrGoi55Gui8TVq/EeulTEG24/zzVZhb6/E7yKvvDRzg5Gg6wyLN6k6UYQHzGRihGGzpWghNYJjSD8Xr1OE4HnfI3OTY6O5wzi/fV8bhd9X/EnSozPg5rS8bqOqN8fW9G1LgeleMyQ+5BBwDQl1dAIdCdDZ+9XybDdrNRFQy0eTpLoxYu71WHKEnQieaj7jiosgUWeTvPtkPiWzpfh+xAd8eY8OuYo9Zg+EpYwVg4uG56NcocydGfU9XxZ//dny7yAeQtpc7cZU1oq9z5M0Wugv1drkbz4ldznRNy0U8NlorSw5/ebLXJF0+0D3bzRiMyqa/RPkAfYThJRHc1HZG36hrmYQ+lQx9qcRegNSF+6vHlrYuGtFoGtVBlAaLgR9KhX6kOLYrPM=
  app: dibs-server
    on:
      repo: mike-crane/dibs-server