language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: C52PlV4Y+85/2cN97LQNkz70qcJ0fMLwAltE9vDMwPPnOl52BFwtyzpDwxp13guxH5kqHGmW7mEAsPMuttdiuzwcGorS4xMaUfppd/+YQ7Ekw0rHTZXZIN/4JsVOa7fV8THOzjbiXY85ExqS073BjiKjhIescEc/FqmkwrYkc+DAaUu8mEsfA0dAJzheTdx7K3+hw6U8x0CMH1F0NfRrIxI9qaY0Ou7I8licT/2zDyG+d9SK5ACxSkgWPt67G59YgXQ+q7LmJ8oa9Es6BNA6aiF/+XGbZjUPAm34zXG+MC0ZE5ogtF70H4FIotEc4zsitbDbJMSjPI1tQt2CVeEuzsuph7Gcf96vVy3bZJelvvV0p1NJjHNLWWFuyX24ZF2PiJ0faBFTN3yNhPQDQOiNzf8o33FAOPOVHJqXFXkt1dJOXVIWWP4o762DESLQSdm75RJXXUs8EGSiLcbM3tLUfFtA5ZIHsapjjcoRr7jnK8YyBmC5IOeGW/PlnlzlLyEO2RfBvpnbbJeQxx7x6kdlu0tRZfpUgaq/rioZa8tYiO0TC/7bGrCeW1xVlsHNz+QpbknfPHP0J364mXsCci9Bjc1L5wTna9zJoS5QCYWvIw5gEdmpArwGZAJcM5liq9whmcMtNRzlB1Nt1YKDxbo/c2DmxXwUMUqU4L7pW+2ZT9s=
  app: dibs-server
  skip_cleanup: true
  on:
    repo: mike-crane/dibs-server