language: node_js
node_js: node
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: nhvBXQuiBINuAMJ+W9PmBXs8nypycPLhWRF1n/W/3huCBPdOLYyLge4IA2Y1pigVhDKPkSx7e/GKmZI+xupu/tOAxbMAS/drNwc4M+Tj/F50q2huE2Ia5eM7fZwRax9CVRvGAwF9bDa0H1mV6T2dqUK2Rk/up78nXF6LOYmlSGoM2evAE+6S2coHbtANrUs3CKqpgKXSUrphXyT19JupnJ6NPAshMwjYuONtglDjgpRGHRlWmAj/FC0Gr9MhZ6CF2ugA3fHn3PpoHM1M7qJKP3sLCTn6B+ytyIpocpZbvYzbXFyqVuMekR+5MN3316Uo7/7tyeaxfjoHYR6/n793gzxwzajn5xmJ3e4x2sGDEXw5j+hLHEGwTjIXAqgj8aSq0c5fxWrbPy2VGu7jSFjxZGOmq2nZxBXGjE5fQKn1uR0PhB8krK2UL2tRISZiXCPcpNqIFlaMWAvftZ9+TLD2BI/RxaGZPvy1n13dDwoMQej7tRJGyfhQGrBcxsgDPsFIMAjIZ8i9qNvXSBigy/2zU4UIaOHX7RycJvCVfoNwsgrE7sqM2lseU8rrukNRAycSEYZUuVkEcTBtKoaIcgVg2hHnbeGPggdsU/gPMmuYIIqyAm7bDBaz6qhvq/dlx04HeFucOlBUmMl9FcK7VaBYk/wx2qOfmGR3YM/k53d/cW8=
  app: gentle-hollows-75217
  on:
    repo: mike-crane/dibs-server
